# Generated by Django 4.0 on 2021-12-16 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='商品价格')),
                ('avg_star', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='商品评分')),
                ('mon_sale', models.IntegerField(verbose_name='月销量')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='供应商名称')),
                ('address', models.CharField(max_length=128, verbose_name='供应商地址')),
                ('telephone', models.IntegerField(verbose_name='供应商电话')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True, verbose_name='购买时间')),
                ('star', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='商品评分')),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.dish', verbose_name='商品id')),
            ],
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='窗口名称')),
                ('place', models.CharField(max_length=128, verbose_name='窗口位置')),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='平均价格')),
                ('avg_star', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='平均评价')),
                ('mon_sale', models.IntegerField(verbose_name='月销量')),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.provider', verbose_name='供应商id')),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
        migrations.RemoveField(
            model_name='books',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='Librarian',
        ),
        migrations.RemoveField(
            model_name='image',
            name='books',
        ),
        migrations.RemoveField(
            model_name='user',
            name='books',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.AddField(
            model_name='purchase',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.user', verbose_name='用户id'),
        ),
        migrations.AddField(
            model_name='dish',
            name='win_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.window', verbose_name='窗口id'),
        ),
        migrations.AddField(
            model_name='image',
            name='dish',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catering.dish', verbose_name='商品'),
        ),
    ]
