# Generated by Django 4.0 on 2021-12-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0002_dish_provider_purchase_window_remove_author_books_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='telephone',
            field=models.CharField(max_length=12, verbose_name='供应商电话'),
        ),
    ]
