# Generated by Django 4.0 on 2021-12-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0004_alter_dish_avg_star_alter_dish_mon_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=12, null=True, verbose_name='学工号'),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=12, null=True, verbose_name='用户电话'),
        ),
    ]
