# Generated by Django 4.0 on 2021-12-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0005_user_number_user_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='star',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='商品评分'),
        ),
    ]
